// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  读取完整应用配置；各字段缺失或无法识别时逐项回落默认值 */
	getConfig: () => typedError<Config_Serialize, CommandError>(__TAURI_INVOKE("get_config")),
	/**  重置全部已知配置项为默认值，返回写后的完整配置 */
	resetConfig: () => typedError<Config_Serialize, CommandError>(__TAURI_INVOKE("reset_config")),
	/**
	 *  局部更新配置：只写提交的字段，返回写后的完整配置（前端据此回写内存态，无需再读一次）。
	 *  界面语言亦经此切换——运行时 `rust_i18n` 由 `config::apply_runtime_effects` 统一同步。
	 */
	updateConfig: (patch: ConfigPatch) => typedError<Config_Serialize, CommandError>(__TAURI_INVOKE("update_config", { patch })),
	/**  采集运行平台信息；单项缺失时回落 `"unknown"`，绝不抛错 */
	getSystemInfo: () => typedError<SystemInfo, CommandError>(__TAURI_INVOKE("get_system_info")),
	/**  真退出应用进程；调用后进程结束，结果体永不可达（按 `CommandResult<()>` 保持命令类型统一） */
	quitApp: () => typedError<null, CommandError>(__TAURI_INVOKE("quit_app")),
	/**  在系统文件管理器中打开日志目录 */
	openLogDir: () => typedError<null, CommandError>(__TAURI_INVOKE("open_log_dir")),
	/**  在系统文件管理器中打开配置目录（`config.json` 所在目录） */
	openConfigDir: () => typedError<null, CommandError>(__TAURI_INVOKE("open_config_dir")),
	/**  复制系统信息到剪贴板；文本由后端组装，前端只调命令 */
	copySystemInfo: () => typedError<null, CommandError>(__TAURI_INVOKE("copy_system_info")),
	/**  转换数据格式；`from` 为空即自动识别。业务失败装进 `ConvertOutcome`，本命令几乎恒返回 `Ok`。 */
	convertData: (input: string, from: "json" | "yaml" | "toml" | "xml" | "ini" | "properties" | null, to: ConvertFormat, options: ConvertOptions) => typedError<ConvertOutcome, CommandError>(__TAURI_INVOKE("convert_data", { input, from, to, options })),
	/**  复制转换结果到系统剪贴板；纯文本直写（需 `AppHandle`，故走 `cores`，与 `copy_system_info` 同模式） */
	copyText: (text: string) => typedError<null, CommandError>(__TAURI_INVOKE("copy_text", { text })),
	/**  检查更新；无新版返回 `None`（仅桌面端有更新能力） */
	checkUpdate: () => typedError<{
	/**  远端版本号 */
	version: string,
	/**  当前版本号 */
	current_version: string,
	/**  发布说明（`latest.json` 的 `body`，可能缺失） */
	body: string | null,
} | null, CommandError>(__TAURI_INVOKE("check_update")),
	/**
	 *  下载并安装更新，进度经 `app-updater-progress` 事件推送；
	 *  装完不自动重启，由前端手动触发（仅桌面端有更新能力）
	 */
	downloadAndInstallUpdate: () => typedError<null, CommandError>(__TAURI_INVOKE("download_and_install_update")),
	/**
	 *  重启应用以完成更新；桌面端本命令不返回，前端调用时不要 `await`
	 *  （移动端返回错误，前端经 `.failed()` 处理）
	 */
	restartApp: () => typedError<null, CommandError>(__TAURI_INVOKE("restart_app")),
};

/* Types */
/**  关闭窗口行为：落盘值为 `snake_case` 字符串，未知一律回落弹窗提示 */
export type CloseBehavior = "prompt" | "exit" | "minimize_to_tray";

/**
 *  命令统一返回的错误类型。
 * 
 *  `serde` 表示即前端契约：序列化为 `{ kind, message }`，前端 `.failed()` 回调按此形状收参。
 */
export type CommandError = 
/**  内部错误（`anyhow` 的链式上下文会展开成可读文本） */
{ kind: "Internal"; message: string };

/**
 *  应用完整配置：各持久化项聚合于此，`store` 内仍按扁平键（`KEY_*`）逐项存储。
 *  新增字段必须能 `Default`（否则旧文件缺键会解析失败）；写路径统一走 `apply_patch` 逐键写入，
 *  禁止用陈旧的 `Config` 整体覆盖。
 * 
 *  新增一个配置项的固定步骤：
 *  `KEY_*` 常量 → 本结构体加字段 → `ConfigPatch` 加同名 `Option` 字段 → `load_config` 回填
 *  → 需要运行时副作用则加进 `apply_runtime_effects` → `reset_patch` 补默认值
 *  → 需跨键规整（如托盘关闭时禁最小化）则加进 `coerce_patch` → `cargo test` 重生成绑定。
 * 
 *  只有**改动已有字段的语义或位置**时才需要递增 `CURRENT_SCHEMA_VERSION` 并在 `MIGRATIONS`
 *  末尾补一级迁移，否则老用户配置会静默失效（纯新增字段由 `Default` + 容错读取兜住）。
 *  布尔开关天然扁平并存（与 `store` 扁平键一一对应），不为 lint 拆结构。
 */
export type Config = Config_Serialize | Config_Deserialize;

/**  局部更新补丁：字段缺省或为 `null` 均表示"不改该键"，非 `null` 表示写入该值 */
export type ConfigPatch = {
	/**  界面语言 */
	locale?: Locale | null,
	/**  开机自启 */
	auto_start?: boolean | null,
	/**  记住窗口状态 */
	remember_window?: boolean | null,
	/**  自动检查更新 */
	auto_check_update?: boolean | null,
	/**  系统托盘开关 */
	tray_enabled?: boolean | null,
	/**  关闭窗口行为 */
	close_behavior?: CloseBehavior | null,
};

/**
 *  应用完整配置：各持久化项聚合于此，`store` 内仍按扁平键（`KEY_*`）逐项存储。
 *  新增字段必须能 `Default`（否则旧文件缺键会解析失败）；写路径统一走 `apply_patch` 逐键写入，
 *  禁止用陈旧的 `Config` 整体覆盖。
 * 
 *  新增一个配置项的固定步骤：
 *  `KEY_*` 常量 → 本结构体加字段 → `ConfigPatch` 加同名 `Option` 字段 → `load_config` 回填
 *  → 需要运行时副作用则加进 `apply_runtime_effects` → `reset_patch` 补默认值
 *  → 需跨键规整（如托盘关闭时禁最小化）则加进 `coerce_patch` → `cargo test` 重生成绑定。
 * 
 *  只有**改动已有字段的语义或位置**时才需要递增 `CURRENT_SCHEMA_VERSION` 并在 `MIGRATIONS`
 *  末尾补一级迁移，否则老用户配置会静默失效（纯新增字段由 `Default` + 容错读取兜住）。
 *  布尔开关天然扁平并存（与 `store` 扁平键一一对应），不为 lint 拆结构。
 */
export type Config_Deserialize = {
	/**  配置结构版本：旧文件缺键时回落 `0`，任何写入都会带上当前版本号 */
	schema_version?: number,
	/**  界面语言：缺失、类型不符或无法识别时回落默认值，绝不让整包解析失败 */
	locale?: Locale,
	/**  开机自启：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	auto_start?: boolean,
	/**  记住窗口状态：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	remember_window?: boolean,
	/**  自动检查更新：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	auto_check_update?: boolean,
	/**  系统托盘开关：缺失或类型不符时回落默认值（`true`），绝不让整包解析失败 */
	tray_enabled?: boolean,
	/**  关闭窗口行为：缺失、类型不符或无法识别时回落弹窗提示，绝不让整包解析失败 */
	close_behavior?: CloseBehavior,
};

/**
 *  应用完整配置：各持久化项聚合于此，`store` 内仍按扁平键（`KEY_*`）逐项存储。
 *  新增字段必须能 `Default`（否则旧文件缺键会解析失败）；写路径统一走 `apply_patch` 逐键写入，
 *  禁止用陈旧的 `Config` 整体覆盖。
 * 
 *  新增一个配置项的固定步骤：
 *  `KEY_*` 常量 → 本结构体加字段 → `ConfigPatch` 加同名 `Option` 字段 → `load_config` 回填
 *  → 需要运行时副作用则加进 `apply_runtime_effects` → `reset_patch` 补默认值
 *  → 需跨键规整（如托盘关闭时禁最小化）则加进 `coerce_patch` → `cargo test` 重生成绑定。
 * 
 *  只有**改动已有字段的语义或位置**时才需要递增 `CURRENT_SCHEMA_VERSION` 并在 `MIGRATIONS`
 *  末尾补一级迁移，否则老用户配置会静默失效（纯新增字段由 `Default` + 容错读取兜住）。
 *  布尔开关天然扁平并存（与 `store` 扁平键一一对应），不为 lint 拆结构。
 */
export type Config_Serialize = {
	/**  配置结构版本：旧文件缺键时回落 `0`，任何写入都会带上当前版本号 */
	schema_version: number,
	/**  界面语言：缺失、类型不符或无法识别时回落默认值，绝不让整包解析失败 */
	locale: Locale,
	/**  开机自启：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	auto_start: boolean,
	/**  记住窗口状态：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	remember_window: boolean,
	/**  自动检查更新：缺失或类型不符时回落 `false`，绝不让整包解析失败 */
	auto_check_update: boolean,
	/**  系统托盘开关：缺失或类型不符时回落默认值（`true`），绝不让整包解析失败 */
	tray_enabled: boolean,
	/**  关闭窗口行为：缺失、类型不符或无法识别时回落弹窗提示，绝不让整包解析失败 */
	close_behavior: CloseBehavior,
};

/**
 *  业务错误体：扁平结构便于 `specta` 导出，前端按 `code` 分支；
 *  `line`/`column` 为 1 基位置（解析器给不出时为 `None`，前端仅有值时渲染"第 N 行"）
 */
export type ConvertError = {
	code: ErrorCode,
	format: ConvertFormat | null,
	message: string | null,
	line: number | null,
	column: number | null,
};

/**  可转换的数据格式：六变体一次定全，稳定前后端契约（线上传 `lowercase`，与前端下拉取值一致） */
export type ConvertFormat = "json" | "yaml" | "toml" | "xml" | "ini" | "properties";

/**  转换选项（输出端高级选项；无选项的格式忽略对应字段） */
export type ConvertOptions = {
	json_indent: JsonIndent,
	xml_root_name: string,
	xml_declaration: boolean,
	xml_indent: JsonIndent,
	ini_kv_separator: IniKvSeparator,
	properties_escape_unicode: boolean,
	xml_trailing_newline: boolean,
};

/**  转换结果：`ok` 为真时读 `output`/`detected`，为假时读 `error`（输出端保留上次成功内容） */
export type ConvertOutcome = {
	ok: boolean,
	output: string,
	detected: ConvertFormat | null,
	error: ConvertError | null,
};

/**  业务错误码：前端按码映射 i18n 文案，`format`/`message` 只做诊断补充（解析器原文，保持英文） */
export type ErrorCode = "TooLarge" | "UnknownFormat" | "ParseFailed" | "UnsupportedInput" | "UnsupportedOutput" | "NonTableRoot" | "UnsupportedValue";

/**  INI 键值分隔符（输出端高级选项） */
export type IniKvSeparator = "compact" | "spaced";

/**  JSON 缩进选项（输出端高级选项；XML 缩进复用同一枚举） */
export type JsonIndent = "two" | "four" | "tab";

/**  应用支持的语言 */
export type Locale = "en" | "zh-CN";

/**  运行平台信息：经 `tauri-plugin-os` 采集，全字段必填，前端逐行展示 */
export type SystemInfo = {
	/**  操作系统平台（如 `linux` / `windows` / `macos`） */
	platform: string,
	/**  操作系统版本 */
	os_version: string,
	/**  系统架构（如 `x86_64`） */
	arch: string,
	/**  主机名 */
	hostname: string,
};

/**  可用的更新信息：只含前端展示所需字段，插件的 `Update` 句柄不出命令边界 */
export type UpdateInfo = {
	/**  远端版本号 */
	version: string,
	/**  当前版本号 */
	current_version: string,
	/**  发布说明（`latest.json` 的 `body`，可能缺失） */
	body: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

